### ISSUE TITLE
Неверный формат даты при редактировании поста

### ISSUE THREAD

**Issue by sendelufa** [sendelufa/jd0#16]
![image](https://user-images.githubusercontent.com/10711828/82927364-0f60bf00-9f9a-11ea-947d-f9650daf54c9.png)

**Comment by sortedmap** [comment]
Вот тут есть вариация этой задачи: https://gitlab.net-page.ru/netpage/skillbox-java-frontend/-/issues/26
Ожидает твоего ответа)

**Comment by sendelufa** [comment]
Решение этого будет через замену даты времени на формат UTC
