### ISSUE TITLE
Добавить требования к ресайзу аватарки на сервере при загрузке

### ISSUE THREAD

**Issue by sendelufa** [sendelufa/jd0#3]
при загрузке аватарки в большом размере, показывает в комментарии в оригинальном размере

написать что требуется ресайзить картинку до 100 пк на сервере

**Comment by sortedmap** [comment]
Дописать про необходимость ресайза в /api/profile/my
Задачу на фронт добавили — https://gitlab.net-page.ru/netpage/skillbox-java-frontend/-/issues/23

**Comment by sendelufa** [comment]
при загрузке аватарки добавлены требования по ресайзу при загрузке до 36 пикселей в виде квадрата.
