### ISSUE TITLE
Формулировка параметра count не описана полностью

### ISSUE THREAD

**Issue by sendelufa** [sendelufa/jd0#4]
count в ответах это количетсво постов по данной выборке
требуется добавить для каждого запроса поста и поиска по ним

**Comment by sortedmap** [comment]
Формулировка:

Параметр count всегда содержит общее количество постов, которое доступно по данному запросу с учётом всех фильтров и параметров, кроме offset и limit.

Написать дополнительные примеры: один запрос с разными offset и limit должен выводить одно и то же значение count.

**Comment by sendelufa** [comment]
https://github.com/sendelufa/jd0/commit/7e41b79eb93205bc0010a4e0606be6ab89af7ede
