### ISSUE TITLE
Уточнить корректность параметра year для получения календаря

### ISSUE THREAD

**Issue by sendelufa** [sendelufa/jd0#5]
Метод выводит количества публикаций на каждую дату переданного в параметре year года или текущего года, если параметр year не задан или **ошибочен**.

Yury Shchegolev, [04.05.20 00:15]
Просто лучше уточнить ТЗ. Отсутствие постов в году еще не ошибка...но если год 1181 или 2021 - то уже ошибка

указать, что необходимо за ошибочное принимать года в будущем, а также все до 1970 года.

**Comment by sortedmap** [comment]
Убираем "или ошибочен". Всегда возвращаем список событий на переданный год, даже если их нет (пустой список)

**Comment by sortedmap** [comment]
Проверить, как фронт реагирует на будущие года, если ему их вернуть с сервера
