### ISSUE TITLE
нет блоков errors в примерах ответа при ошибке

### ISSUE THREAD

**Issue by sendelufa** [sendelufa/jd0#6]
Регистрация 
Авторизация и прочие при 
Result: false

**Comment by sortedmap** [comment]
Дописать доп. параметры в форматы ответов при ошибках. Например, добавить message туда, где он может быть показан фронтом

**Comment by sortedmap** [comment]
Частный случай этой задачи — #1

**Comment by sortedmap** [comment]
Где-то накапливаем идеи по ошибкам?

**Comment by sendelufa** [comment]
по ошибкам тоже все фиксы есть
