### ISSUE TITLE
формат запроса на бэк при регистрации 

### ISSUE THREAD

**Issue by sendelufa** [sendelufa/jd0#7]
@sendel еще момент - /api/auth/register в ТЗ также описано, что передаются параметры, по факту - json в хедере

**Comment by sendelufa** [comment]
перечислить подробнее в каком формате отпарвляются данные вов всех запросах

**Comment by sortedmap** [comment]
В случае, если отправляется в теле запроса в JSON, так и написать: "Параметры (отправляются в теле запроса в формате JSON): {...}"

**Comment by sendelufa** [comment]
перечислены все примеры запросов с фронта в виде параметров или json
